# This is a basic workflow to help you get started with Actions

name: CI_
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line scrip
        run: echo Hello, world!
        
  Linter:
    name: Checking Test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v1
      - uses: actions/checkout@master
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "./coverage/lcov.info"
          min_coverage: 10

